name: Run NV Simulator

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  simulate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run simulation
      run: |
        python nv_simulator.py
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pulse-image
        path: pulse_histogram.png
